import Header from "@/components/Header";
import Footer from "@/components/Footer";

export default function Terms() {
    return (
        <>
            <Header />
            <div className="container-fluid dark-bg" style={{ padding: "0px" }}>
                <div className="text-center container py-5">
                    <h1 className="site-green fix-mt fix-mt-sm monstText">
                        Terms and Conditions
                    </h1>
                    <p className="xsmall grey-color-2">
                        ATTENTION: YOU MUST BE AT LEAST 18 YEARS OF AGE TO ENTER INTO THIS AGREEMENT AND USE Peershieldex
                    </p>
                </div>
            </div>
            <div className="conatiner-fluid">
                <div className="container py-5">
                    <h5 className="meri-weda">ACCEPTANCE OF TERMS AND CONDITIONS</h5>
                    <p className="xsmall grey-color-2">
                        Peershieldex provides a collection of online resources, including escrow services for bitcoin transactions (hereinafter, "the Service") subject to the following Terms and Conditions of Use ("Terms and Conditions"), which may be updated by Peershieldex from time to time. Unless explicitly stated otherwise, any new features that augment or enhance the current Service shall be subject to the Terms and Conditions. Peershieldex will provide notice of significant changes to the Terms and Conditions by posting notice of said changes on Peershieldex website. In addition, when using the Service, you shall be subject to any posted guidelines or rules applicable to the Service, which may be posted from time to time. All such guidelines and rules are hereby incorporated by reference into the Terms. By using the Service in any way, you are agreeing to comply with these Terms and Conditions. In order to use the Service, you must obtain access to the World Wide Web, either directly or through devices that access web-based content, and pay any service fees associated with such access. In addition, you must provide all equipment necessary to make such connection to the World Wide Web, including a computer and a modem or other access device. The Service is offered to you conditioned on your acceptance without modification of the terms, conditions, and notices contained herein. Should you object to any part of these Terms and Conditions, any guidelines, or any subsequent modifications thereto or become dissatisfied with Peershieldex in any way, your only recourse is to immediately discontinue use of Peershieldex.
                    </p>

                    <h5 className="meri-weda mt-4">ONLINE CONTENT</h5>
                    <p className="xsmall grey-color-2">
                        You understand that all postings, messages, text or other materials ("Content") posted on, transmitted through, or linked from the Service, are the sole responsibility of the person from whom such Content originated and should not necessarily be relied upon. This means that you, and not the owner(s) of Peershieldex, are entirely responsible for all Content that you publish, display, post, email or otherwise make available and/or transmit via the Service. You understand that Peershieldex does not control, and is not responsible for Content made available and/or transmitted through the Service, and that by using the Service, you may be exposed to Content that is inaccurate, misleading, or otherwise objectionable. Not only does Peershieldex not control the content posted and transmitted via the Service, but the owner(s) of Peershieldex also does not guarantee the accuracy, completeness, timeliness or usefulness of any information on the Service and neither adopts nor endorses nor is responsible for the accuracy or reliability of any opinion, advice, statement, representation or promise made. Furthermore, Peershieldex site and Content available through the Service may contain links to other websites, which are completely independent of Peershieldex and the owner(s) of Peershieldex.
                    </p>
                    <p className="xsmall grey-color-2">
                        Peershieldex makes no representation or warranty as to the accuracy, completeness or authenticity of the information contained in any such site. Your linking to any other websites is at your own risk. You agree that you must evaluate, and bear all risks associated with, the use of any Content, that you may not rely on said Content, and that under no circumstances will the owner(s) of Peershieldex be liable in any way for any Content or for any loss or damage of any kind incurred as a result of the use of any Content posted, emailed or otherwise made available and/or transmitted via the Service. You acknowledge that Peershieldex does not pre-screen, pre-qualify or approve Content, but that Peershieldex shall have the right (but not the obligation) in its sole discretion to refuse, delete or move any Content that is available via the Service, for violating the letter or spirit of the Terms and Conditions or the law or for any other reason
                    </p>
                    {/* #### */}
                    <h5 className="meri-weda mt-4">USER CONDUCT</h5>
                    <p className="xsmall grey-color-2">
                        You agree not to post, email, or otherwise make available Content: (a) that is unlawful, harmful, threatening, abusive, harassing, defamatory, pornographic, libellous, invasive of another's privacy, or harms minors in any way; (b) that harasses, degrades, intimidates or is hateful toward an individual or group of individuals on the basis of religion, gender, sexual orientation, race, ethnicity, age, or disability; (c) that impersonates any person or entity, including, but not limited to, a Peershieldex employee, or falsely states or otherwise misrepresents your affiliation with a person or entity; (d) that includes personal or identifying information about another person without that person's explicit consent; (e) that is false, deceptive, misleading, deceitful, or constitutes "bait and switch"; (f) that infringes any patent, trademark, trade secret, copyright or other proprietary rights of any party, or Content that you do not have a right to make available under any law or under contractual or fiduciary relationships; (g) that constitutes or contains "affiliate marketing," "link referral code," "junk mail," "spam," "chain letters," "pyramid schemes," or unsolicited commercial advertisements; (h) that constitutes or contains any form of advertising or solicitation if posted in areas of Peershieldex site which are not designated for such purposes; (i) that includes links to commercial services or websites, including but not limited to local market related services, except as allowed in "Peershieldex ads"; (j) that advertises any illegal services or the sale of any items the sale of which is prohibited or restricted by applicable law, including without limitation items the sale of which is prohibited or regulated by the laws of any of the states or territories of South Africa; (k) that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment (l) that disrupts the normal flow of dialogue with an excessive number of messages (flooding attack) to the Service, or that otherwise negatively affects other users' ability to use the Service, or; (m) that employs misleading email addresses, or forged headers or otherwise manipulated identifiers in order to disguise the origin of Content transmitted through the Service.

                        With respect to other users of the Service, you also agree not to: (n) contact anyone who has asked not to be contacted; (o) "stalk" or otherwise harass anyone; (p) collect personal data about other users for commercial or unlawful purposes; (q) use automated means, including spiders, robots, crawlers, data mining tools, or the like to download data from the Service - exception is made for Internet search engines and non-commercial public archives that comply with our robots.txt file; (r) purposefully post Content in a irrelevant category or city, repeatedly post the same or similar Content or otherwise impose an unreasonable or disproportionately large load on our infrastructure, or; (s) attempt to gain unauthorized access to the Peershieldex computer systems or engage in any activity that disrupts, diminishes the quality of, interferes with the performance of, or impairs the functionality of, the Service or Peershieldex website.
                    </p>
                    <p className="xsmall grey-color-2">
                        Peershieldex maintains a zero tolerance "spam" policy. You understand and agree that sending unsolicited email advertisements to users of the Service or through the Service's computer systems, which is expressly prohibited by these Terms and Conditions, will use or cause to be used servers located in South Africa. Any unauthorized use of Peershieldex computer systems is a violation of these Terms and Conditions and certain federal and state laws, including but not limited to the Computer Fraud and Abuse Act and sections of the various criminal and civil codes of the states, territories of South Africa. Such violations may subject the sender and his or her agents to criminal and/or civil criminal penalties. Peershieldex expressly reserves the right to delete without notice any information posted by an individual who refuses to comply with any of the provisions contained herein.
                    </p>
                </div>
            </div>
            <Footer />
        </>
    )
}
